### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by smi-cetic** [oscar-lib/LearningForOptimizing#4]
Certain components, such as tabu list functionality, are duplicated in several spots. It would be a good idea to put these components in a single place that can be reused instead. There is also need to tidy up the codebase in general, we can probably achieve this with a single PR. Anything you want to highlight @albertofranzin @augustindelecluse ?

**Comment by augustindelecluse** [comment]
I think the list of components should include

- Handle tabu search
- Choose an item within a list, each item having a given weight (similar to the p parameter in [random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html))
- Choose an item within a list, each item having a given weight BUT some items are marked as tabu (almost the same function as above thus)
- Not a definitive idea yet, but for computing a custom reward, [this code](https://github.com/oscar-lib/LearningForOptimizing/blob/be5d383ba038e98b080f41f2924fd2ec6b2791cd/src/main/scala/combinator/BanditCombinator.scala#L24) computing the statistics of a neighborhood seems like a fine approach . We could change the reward functions so that they all take as input such statistics, and update the statistics automatically.

I will fill in this list if something else comes to mind when beginning the refactor

**Comment by smi-cetic** [comment]
Sorry for the wait; @augustindelecluse that sounds like a good list for now. I've created a branch for the PR, we can start adding commits to it.

**Comment by augustindelecluse** [comment]
I've pushed the current changes onto the branch. Here are some notes on the core components:

- The abstract `BanditSelector` class is the new class to override. It contains a tabu list, some common rewards used (for the slope, time and finding a move), a weight update scheme based on a learning rate (that can be easily overridden if necessary) and other utility functions. Two methods are abstract: one for getting the move, one for computing the reward
- I've added an `EpsilonGreedyBanditNew` and a `BestSlopeFirstNew` class overriding this class to highlight the changes. The old ones are still there, and might be removed once we are fine with the code. Moreover, the new bandits can be specified as arguments of the main (`--bandit epsilonGreedyNew` or `BestSlopeFirstNew`).
- The `NeighorhoodStats` is a lightweight class holding information about a move that has been performed (slope, duration, etc.)
- The `LearningScheme` sealed class specifies when to learn, and can be one of three types: `AfterEveryMove`, `AfterNMoves` or `AfterEveryDescent`. The constructor of `BanditSelector` takes an object of this class as argument in its constructor.

Here are some choices that I did but that might worth discussing:
- For updating the weight, they're are performed as `weight(i) = weight(i) + learningRate * reward`. This is not exactly the same as what was done in the previous Epsilon-Greedy for instance (it took the mean of all rewards) but seems to be more widespread in RL
- When the learning mode is set to `AfterNMoves`, resetting the bandit also triggers a learning. This is to prevent situations where a part of the N last moves are done in one descent, and the others in another descent.
